explore package page and optimalization tabs on order page
Cexup-Team/cexup-web pull request #32
Opened 2022-07-12 09:57 UTC by iqbalnurhaq

2022-07-18 03:43 UTC, triandamai commented on parts/Tabs.vue
> +        setTimeout(() => {
spertinya ga perlu pake vanilla js deh...karena kan kita bisa pake ref dll

2022-07-18 03:44 UTC, triandamai requested changes
check dulu

2022-07-18 04:13 UTC, iqbalnurhaq commented on parts/Tabs.vue
> +        setTimeout(() => {
oke, wait

2022-07-18 10:34 UTC, iqbalnurhaq commented
btw yang ref baru itu ya di tab, soalnya ketika ngrubah banyak yang ke dampak

2022-07-19 02:19 UTC, triandamai approved these changes

2022-07-19 02:19 UTC, merged