Impl api on register page, complete page, dashboard page, order page, teleconsultation page, shimmer and more
Cexup-Team/cexup-web pull request #37
Opened 2022-08-12 09:22 UTC by iqbalnurhaq

2022-08-15 08:04 UTC, triandamai requested changes
Cek dulu yagesya

2022-08-15 08:04 UTC, triandamai commented on components/card/Order.vue
> +    import {formatDate} from '../../utils/getFormatDate'
taro di composable aja jadi ga perlu diimport

2022-08-15 08:04 UTC, triandamai commented on composables/data-store-impl.ts
> +        name?: string,
nullable buat apa? pake `""`kan ga papa?

2022-08-15 08:04 UTC, triandamai commented on composables/http-client.ts
> +    get(base: string, url: string, key: string, token: string):Promise<BaseResponse>
bikin 1 function aja buat pemakaian tinggal:
function get 
```ts
get(url:string, token)
```
pemakaian
```ts
this.api.get(`${import.meta.env.VITE_APP_BASE_URL}/speciality/${import.meta.env.VITE_APP_API_KEY}`,token)
```

2022-08-15 08:04 UTC, triandamai commented on composables/data-store-impl.ts
> +        const {success,message,data} = await this.api.get(`${import.meta.env.VITE_APP_BASE_URL}`, `doctor?data=${size}&name=${search}&speciality=${speciality}&hospital=${hospital}`, `${import.meta.en
```ts
this.api.get(`${import.meta.env.VITE_APP_BASE_URL}/speciality/${import.meta.env.VITE_APP_API_KEY}`,token)
```

2022-08-15 08:04 UTC, triandamai commented on composables/data-store-impl.ts
> +        const {success,message,data} = await this.api.get(`${import.meta.env.VITE_APP_BASE_URL}`, `doctor?data=${size}`, `${import.meta.env.VITE_APP_API_KEY}`, token)
```ts
this.api.get(`${import.meta.env.VITE_APP_BASE_URL}/speciality/${import.meta.env.VITE_APP_API_KEY}`,token)
```

2022-08-15 08:04 UTC, triandamai commented on pages/index.vue
> +    const stateDoctor = reactive({
kenapa state nya ga di taro di `store` biar di page ini cuma `dashboard.getProduct()` misal

2022-08-15 08:04 UTC, triandamai commented on stores/dashboard-store.ts
> +
stately taro sini biar di page ga kebanyakan logic

2022-08-15 08:04 UTC, triandamai commented on stores/region-store.ts
> +
stately pinch kesini

2022-08-15 08:04 UTC, triandamai commented on stores/teleconsultation-store.ts
> +
state nya pidah kesini

2022-08-15 08:53 UTC, iqbalnurhaq commented on composables/http-client.ts
> +    get(base: string, url: string, key: string, token: string):Promise<BaseResponse>
yang ini ada dua base url yan dan tokennya beda, dev app sama mecial record, kalau jadi satu gk dinamis

2022-08-16 05:46 UTC, triandamai requested changes
Cek lagi

2022-08-16 05:46 UTC, triandamai commented on pages/auth/index.vue
> +                user.stateLogin.isLoading = false
set staten ya di action aja gausah disini

2022-08-16 05:46 UTC, triandamai commented on pages/auth/index.vue
> +                user.stateLogin.isLoading = false
ini setnya di action jangan disini

2022-08-16 05:46 UTC, triandamai commented on pages/index.vue
> +                dashboard.stateProduct.isData = res.data
ini ngesetnya di action aja jadi gaperlu ada then Karena tugasnya cuma manggil

2022-08-16 05:46 UTC, triandamai commented on pages/index.vue
> +                dashboard.stateArticle.isData = res.data
ini ngesetnya di action aja jadi gaperlu ada then Karena tugasnya cuma manggil

2022-08-16 05:46 UTC, triandamai commented on pages/index.vue
> +                dashboard.stateProduct.isLoading = false
ini ngesetnya di action aja jadi gaperlu ada then Karena tugasnya cuma manggil

2022-08-16 05:46 UTC, triandamai commented on pages/index.vue
> +                dashboard.stateArticle.isStatus = "error"
ini ngesetnya di action aja jadi gaperlu ada then Karena tugasnya cuma manggil

2022-08-16 05:46 UTC, triandamai commented on pages/index.vue
> +                dashboard.stateVitalSign.isData = res.data
ini ngesetnya di action aja jadi gaperlu ada then Karena tugasnya cuma manggil

2022-08-16 05:46 UTC, triandamai commented on pages/index.vue
> +                dashboard.stateVitalSign.isLoading = false
ini ngesetnya di action aja jadi gaperlu ada then Karena tugasnya cuma manggil

2022-08-16 05:46 UTC, triandamai commented on pages/index.vue
> +                dashboard.stateCurrentEWS.isData = res.data
ini ngesetnya di action aja jadi gaperlu ada then Karena tugasnya cuma manggil

2022-08-16 05:46 UTC, triandamai commented on pages/teleconsultation/doctor/[slug].vue
> +                state.isData = res.data
ini ngesetnya di action aja jadi gaperlu ada then Karena tugasnya cuma manggil

2022-08-16 05:46 UTC, triandamai commented on pages/teleconsultation/order/[transaction_id].vue
> +                state.isData = res.data
ini ngesetnya di action aja jadi gaperlu ada then Karena tugasnya cuma manggil

2022-08-16 05:46 UTC, triandamai commented on stores/dashboard-store.ts
> +
set state ya disini yang di return ke view itu cuma status berhasil tau gagal

2022-08-16 05:46 UTC, triandamai commented on stores/teleconsultation-store.ts
> +                    data : data
set state ya disini yang di return ke view itu cuma status berhasil tau gagal

2022-08-19 11:37 UTC, triandamai requested changes
Satu lagi

2022-08-19 11:37 UTC, triandamai commented on pages/teleconsultation/doctor/[slug].vue
> +    const getTime = (date) => {
ini velum dipindah ke store?

2022-08-22 02:59 UTC, triandamai requested changes
Need change little bit

2022-08-22 02:59 UTC, triandamai commented on composables/http-client.ts
> +    async get(base: string, url: string, key: string, token: string): Promise<BaseResponse> {
look's good

2022-08-22 06:41 UTC, triandamai approved these changes
LGTM!

2022-08-22 06:41 UTC, merged